defaults:
  - _self_
  - global_config

model_path: "./results/models/CNN_MULTI/{TBD}" # Need to specify exact model path
config_name: "config_file.yaml"
mode: "env"
split: "val" # test
output_dir: "./results/models/CNN_MULTI"
seed: 42
with_region: True
fwi_ths: [5, 10, 20, 30]
n_plots: 50
size_plots: 6
suffix: "one"

MODEL:
  architecture:  "TabResNetConvLSTM"
  resnet_type: "resnet50"
  pretrained: True
  input_img_res: 264
  img_res: 260
  train_max_seq_len: 5
  val_max_seq_len: 5
  test_max_seq_len: 5
  input_dim: 14
  depth: 5
  encoder_channels: [512, 1024, 2048]
  decoder_channels: [256, 128, 64]
  num_classes: 2
  kernel_size: [3, 3]
  n_stack_layers: 1
  out_H: 26
  out_W: 26
  threshold: 0.5
  multi_head: False
  temp_enc: True

  dropout: 0.
  tab_input_dim: 15
  output_dim: 64
  env_stack_layers: 1
  mask_env: True
  fusion: "late"
  tab_enc: True

SOLVER:
  num_epochs: 20
  num_warmup_epochs: 2
  pos_weight: 6.7
  loss_function:  combined_dice_ce # We could not return an empty mask and use CE loss

### Leveraging RAW *.npy files ###
DATASETS:
  kwargs:
    tab_dir: ["${paths.pos_env_tab}", "${paths.neg_env_tab}"]
    mean_file: "${paths.bands_mean}"
    std_file: "${paths.bands_std}"
    with_loc: False
    with_doy: True
    is_spatial: False
    nan_value: "median"
    # bands: possibility to specify the selected bands.
  train:
    paths: "${paths.split}"
    base_dir: ["${paths.pos_sits}", ${paths.neg_sits}"]
    label_dir: "${paths.label}"
    batch_size: 24
    num_workers: 8

  eval:
    paths: "${paths.split}"
    base_dir: ["${paths.pos_sits}", ${paths.neg_sits}"]
    label_dir: "${paths.label}"
    batch_size: 24
    num_workers: 8
    hard: False

### Leveraging Hf parquet files ###
#DATASETS:
#  mode: "huggingface"
#  kwargs:
#    mean_file: "${paths.bands_mean}"
#    std_file: "${paths.bands_std}"
#    with_loc: False
#    with_doy: True
#    is_spatial: True
#    nan_value: "median"
    # bands: possibility to specify the selected bands.
#  train:
#    data_dir: "${paths.hf_data}"
#    batch_size: 24
#    num_workers: 8
#
#  eval:
#    data_dir: "${paths.hf_data}"
#    batch_size: 24
#    num_workers: 8
#    hard: False