defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "wildfire-forecast"
  user: "hporta"

paths:
  label: "/media/data/boreal_data/labels_update"
  split: "/media/data/boreal_data/full/COPERNICUS/UPDATE/split_one.json"
  split_hard: "/media/data/boreal_data/full/COPERNICUS/UPDATE/split_one_hard.json"
  pos_sits: "/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT"
  neg_sits: "/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT_NEG"
  neg_sits_hard: "/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT_NEG_HARD"
  bands_mean: "/media/data/boreal_data/full/COPERNICUS/UPDATE/bands_mean.json"
  bands_std: "/media/data/boreal_data/full/COPERNICUS/UPDATE/bands_std.json"
  hf_data: "/home/hporta/code_project/wildfire-forecast/wildfire-highres-multimodal/hug_data"
  pos_env_spa: "/media/data/boreal_data/TS_SPATIAL_UPDATE"
  neg_env_spa: "/media/data/boreal_data/NEG_TS_SPATIAL_UPDATE"
  neg_env_spa_hard: "/media/data/boreal_data/NEG_TS_SPATIAL_UPDATE_HARD"
  pos_env_tab: "/media/data/boreal_data/TS_UPDATE"
  neg_env_tab: "/media/data/boreal_data/NEG_TS_UPDATE"
  neg_env_tab_hard: "/media/data/boreal_data/NEG_TS_UPDATE_HARD"
  fwi: "/media/data/boreal_data/full/CDS"