defaults:
  - _self_
  - global_config

regions: ["Ontario", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Nunavut", "Yukon"]
base_dir: ["/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT",
    "/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT_NEG"]
base_dir_hard: ["/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT",
    "/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT_NEG_HARD"]
tab_dir: ["/media/data/boreal_data/TS_UPDATE", "/media/data/boreal_data/NEG_TS_UPDATE"]
env_dir: ["/media/data/boreal_data/TS_SPATIAL_UPDATE", "/media/data/boreal_data/NEG_TS_SPATIAL_UPDATE"]
label_dir: "/media/data/boreal_data/labels_update"
json_file: "/media/data/boreal_data/full/COPERNICUS/UPDATE/split_one.json"
json_file_hard: "/media/data/boreal_data/full/COPERNICUS/UPDATE/split_one_hard.json"
#hug_repo_id: "EPFL-ECEO/CanadaFireSat-Ontario-Img"
hug_repo_id: "EPFL-ECEO/CanadaFireSat-Ontario-Img"
flag_private: True
max_size: 500
