defaults:
  - _self_
  - global_config

#regions: ["Ontario", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Nunavut", "Yukon"]
#regions: ["Quebec"]
#regions: ["British Columbia", "Northwest Territories", "Saskatchewan"]
regions: ["Saskatchewan"]
#regions: ["Northwest Territories"]
base_dir: ["/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT",
    "/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT_NEG"]
base_dir_hard: ["/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT",
    "/media/data/boreal_data/full/COPERNICUS/UPDATE/S2_SERIES_SEAS_FORMAT_NEG_HARD"]
tab_dir: ["/media/data/boreal_data/TS_UPDATE", "/media/data/boreal_data/NEG_TS_UPDATE"]
tab_dir_hard: ["/media/data/boreal_data/TS_UPDATE", "/media/data/boreal_data/NEG_TS_UPDATE_HARD"]
env_dir: ["/media/data/boreal_data/TS_SPATIAL_UPDATE", "/media/data/boreal_data/NEG_TS_SPATIAL_UPDATE"]
env_dir_hard: ["/media/data/boreal_data/TS_SPATIAL_UPDATE", "/media/data/boreal_data/NEG_TS_SPATIAL_UPDATE_HARD"]
label_dir: "/media/data/boreal_data/labels_update"
json_file: "/media/data/boreal_data/full/COPERNICUS/UPDATE/split_one.json"
json_file_hard: "/media/data/boreal_data/full/COPERNICUS/UPDATE/split_one_hard.json"
temp_root: "/home/hporta/code_project/wildfire-forecast/wildfire-highres-multimodal/temp_datasets"
#hug_repo_id: "EPFL-ECEO/CanadaFireSat-Ontario-Img"
hug_repo_id: "EPFL-ECEO/CanadaFireSat"
flag_private: False
max_size: 500
